import React from 'react';
import { motion } from 'framer-motion';
import { Award, ShieldCheck, Zap, Sparkles, FolderGit2, CheckCircle2, TrendingUp } from 'lucide-react';

const SAMPLE_METRICS = [
  {
    label: "ATS Match",
    value: "91%",
    sub: "+14% vs avg benchmark",
    icon: Award,
    highlight: "text-[#4ade80]"
  },
  {
    label: "Resume Quality",
    value: "Excellent",
    sub: "Quantified impact detected",
    icon: ShieldCheck,
    highlight: "text-white"
  },
  {
    label: "Skill Match",
    value: "89%",
    sub: "18 / 20 core skills found",
    icon: Zap,
    highlight: "text-[#4ade80]"
  },
  {
    label: "Interview Readiness",
    value: "High",
    sub: "Top 5% candidate tier",
    icon: TrendingUp,
    highlight: "text-white"
  },
  {
    label: "Recommendations",
    value: "12",
    sub: "Actionable roadmap items",
    icon: Sparkles,
    highlight: "text-amber-400"
  },
  {
    label: "Projects Suggested",
    value: "4",
    sub: "Targeted skill gap fixes",
    icon: FolderGit2,
    highlight: "text-cyan-400"
  }
];

export default function ExecutiveReportPreview() {
  return (
    <section className="w-full space-y-7 text-left">
      {/* Header & Alignment */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-white/10 pb-5">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="inline-block bg-white/5 border border-white/10 px-3 py-0.5 rounded-full text-[0.65rem] uppercase tracking-[1.5px] text-white/80 font-sans">
              Landing Showcase
            </span>
            <span className="text-[10px] text-white/40 uppercase tracking-widest font-mono flex items-center gap-1">
              <CheckCircle2 className="w-3 h-3 text-[#4ade80]" /> Standard Intelligence Output
            </span>
          </div>
          <h2 className="font-['Syne'] font-extrabold text-2xl sm:text-3xl tracking-[-1.5px] text-white">
            Executive AI Report Preview
          </h2>
        </div>
        <p className="text-white/45 text-xs max-w-md font-light leading-relaxed">
          Sample preview of the deep-dive multi-dimensional insights generated by our RAG intelligence engine upon resume ingest.
        </p>
      </div>

      {/* Responsive Grid - Strictly 6 Columns on Desktop (lg & xl) */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 sm:gap-3.5 lg:gap-3.5 xl:gap-4 w-full">
        {SAMPLE_METRICS.map((metric, idx) => {
          const Icon = metric.icon;
          return (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-30px' }}
              transition={{ duration: 0.45, delay: idx * 0.06, ease: [0.22, 1, 0.36, 1] }}
              className="glass-panel-report p-5 flex flex-col justify-between min-h-[160px] hover:scale-[1.02] transition-all cursor-default"
            >
              {/* Icon & Label */}
              <div>
                <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center mb-3">
                  <Icon className="w-4 h-4 text-white/80" />
                </div>

                <span className="text-[11px] text-white/60 uppercase tracking-wide font-medium block mb-2 font-sans">
                  {metric.label}
                </span>

                <span className={`font-['Syne'] font-bold text-[28px] sm:text-[30px] leading-tight block ${metric.highlight}`}>
                  {metric.value}
                </span>
              </div>

              {/* Supporting Caption */}
              <span className="text-[12px] text-white/70 leading-[1.4] font-light block mt-3 whitespace-normal break-words">
                {metric.sub}
              </span>
            </motion.div>
          );
        })}
      </div>
    </section>
  );
}
