from pydantic import BaseModel, Field
from typing import List, Dict, Any

class ScoreDetail(BaseModel):
    score: int = Field(..., description="The calculated score for this category")
    max: int = Field(..., description="The maximum possible score for this category")
    explanation: str = Field(..., description="Detailed feedback explaining why this score was given")

class ScoreBreakdown(BaseModel):
    technical_skills: ScoreDetail = Field(..., description="Technical skills evaluation")
    experience: ScoreDetail = Field(..., description="Work experience timeline evaluation")
    projects: ScoreDetail = Field(..., description="Projects quantity and stack evaluation")
    keyword_match: ScoreDetail = Field(..., description="Industry-specific terminology alignment")
    education: ScoreDetail = Field(..., description="Educational credentials alignment")
    resume_quality: ScoreDetail = Field(..., description="Format and metadata quality evaluation")

class SkillGapItem(BaseModel):
    skill: str = Field(..., description="Name of the missing or weak skill")
    importance: str = Field(..., description="Why this skill is important for the target role")
    ats_impact: str = Field(..., description="How missing this skill affects the ATS score")
    usage: str = Field(..., description="Where it is commonly utilized in the role daily duties")
    learning_direction: str = Field(..., description="Recommended learning resources or steps")

class ResumeQualityReport(BaseModel):
    linkedin_found: bool = Field(..., description="Whether LinkedIn profile was found")
    github_found: bool = Field(..., description="Whether GitHub profile was found")
    portfolio_found: bool = Field(..., description="Whether a personal portfolio website was found")
    achievements_quantified: bool = Field(..., description="Whether resume contains metric-driven achievements (%, $, numbers)")
    resume_length_pages: int = Field(..., description="Estimated page length of the resume")
    recommendations: List[str] = Field(..., description="Actionable tips to improve overall formatting, links, and text density")

class ProjectSuggestion(BaseModel):
    title: str = Field(..., description="Project title")
    description: str = Field(..., description="Actionable personalized description of what to build to bridge the gap")
    tech_stack: List[str] = Field(..., description="List of technologies to use in the project")
    difficulty: str = Field(..., description="Difficulty tier: Beginner, Intermediate, or Advanced")

class CertificationSuggestion(BaseModel):
    name: str = Field(..., description="Certification name")
    provider: str = Field(..., description="Institution providing the cert")
    skills_covered: List[str] = Field(..., description="List of skills that will be learned")

class KeywordBreakdownItem(BaseModel):
    keyword: str = Field(..., description="Role-specific keyword analyzed")
    found: bool = Field(..., description="Whether keyword is found in the resume")

class InterviewReadiness(BaseModel):
    score: int = Field(..., description="Readiness score from 1 (unprepared) to 5 (excellent)")
    explanation: str = Field(..., description="Reasoning behind the readiness score")

class AnalysisReport(BaseModel):
    ats_score: int = Field(..., description="Python-calculated overall final ATS score out of 100")
    score_breakdown: ScoreBreakdown = Field(..., description="Section-by-section breakdown with educational reasoning")
    summary: str = Field(..., description="Professional candidate alignment summary generated by Gemini")
    strengths: List[str] = Field(..., description="List of candidate's key strengths")
    missing_skills: List[str] = Field(..., description="List of missing skills identified relative to the target role")
    skill_gap_analysis: List[SkillGapItem] = Field(..., description="Granular explanations of gaps and learning paths")
    suggestions: List[str] = Field(..., description="Actionable recommendations to improve the resume content")
    resume_quality_analysis: ResumeQualityReport = Field(..., description="Metadata and links verification report")
    recommended_projects: List[ProjectSuggestion] = Field(..., description="Personalized projects based on the projects database to bridge missing skills")
    recommended_certifications: List[CertificationSuggestion] = Field(..., description="Personalized certifications recommendation list")
    keyword_breakdown: List[KeywordBreakdownItem] = Field(..., description="Detailed table map of target keywords found/missing")
    interview_readiness: InterviewReadiness = Field(..., description="Assessment of candidate's interview preparation level")
    verdict: str = Field(..., description="Overall fit: Excellent Match, Good Match, Average Match, or Needs Improvement")

class AnalyzeResponse(BaseModel):
    session_id: str
    analysis: AnalysisReport

class ChatResponse(BaseModel):
    reply: str
